INSERT INTO lygStyleSize (StyleCode, SizeSort, SizeName)
VALUES
('BOSSE FANCY OH HOOD S.9', 1, 'XS'),
('BOSSE FANCY OH HOOD S.9', 2, 'S'),
('BOSSE FANCY OH HOOD S.9', 3, 'M'),
('BOSSE FANCY OH HOOD S.9', 4, 'L'),
('BOSSE FANCY OH HOOD S.9', 5, 'XL'),
('BOSSE FANCY OH HOOD S.9', 6, 'XXL'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 1, '92'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 2, '98'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 3, '104'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 4, '110'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 5, '116'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 6, '122'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 7, '128'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 8, '134'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 9, '140'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 10, '146'),
('FOOTBALL SETS EUROCUP CW N (ARGENTINA) S.9', 11, '152');


